#!/usr/bin/env python3
from __future__ import annotations

import argparse
import datetime as _dt
import sys
from pathlib import Path


def _read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _write_text(path: Path, content: str, *, force: bool) -> None:
    if path.exists() and not force:
        raise FileExistsError(f"Refusing to overwrite existing file: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _render(template: str, mapping: dict[str, str]) -> str:
    rendered = template
    for key, value in mapping.items():
        rendered = rendered.replace(f"{{{{{key}}}}}", value)
    return rendered


def _create_directory_structure(out_dir: Path) -> dict[str, Path]:
    dirs = {
        "root": out_dir,
        "templates": out_dir / "templates",
        "diagrams": out_dir / "diagrams",
        "doc": out_dir / "doc",
        "ppt": out_dir / "ppt",
        "manifest": out_dir / "manifest",
    }
    for d in dirs.values():
        d.mkdir(parents=True, exist_ok=True)
    return dirs


def _write_readme(out_dir: Path, mapping: dict[str, str]) -> None:
    project = mapping.get("PROJECT_NAME", "TBD")
    readme = f"""# {project} — Delivery Artifact Pack

Generated by scaffold_artifacts.py on {mapping.get("DATE", "TBD")}.

## Directory Structure

```
{out_dir.name}/
├── templates/          # Filled-in markdown templates (Phase 0-8 + packaging)
├── diagrams/           # Diagram source files (.drawio, .svg)
│   ├── drawio/         # drawio-skill outputs (architecture, topology, C4, swimlane, flowchart)
│   └── fireworks/      # fireworks-tech-graph outputs (agent arch, data flow, mind map, flowchart)
├── doc/                # Final client-facing document (DOCX) + embedded images
├── ppt/                # Final executive presentation (PPTX) + embedded images
└── manifest/           # Diagram manifest + delivery package manifest
```

## Diagram Production Guide

Consult `references/diagram-guide.md` in the skill for:
- Which skill to use at each phase (drawio-skill vs fireworks-tech-graph)
- Recommended diagram types and export formats
- Tips for each diagram

### Diagram Skills

- **drawio-skill**: For architecture, C4 models, swimlanes, network topology, flowcharts → produces `.drawio` + `.png`
- **fireworks-tech-graph**: For agent architecture, data flow, mind maps, comparison matrices → produces `.svg` + `.png`

## Next Steps

1. Fill in the `templates/` markdown files with project-specific content.
2. Produce diagrams per `templates/08_diagram_manifest.md` — invoke the diagram skills as needed.
3. At Phase 7.5, compile all artifacts into DOCX + PPTX using `templates/07_deliverable_packaging.md`.
4. Archive the complete delivery package.
"""
    _write_text(out_dir / "README.md", readme, force=True)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        description="Generate a standard agent/LLM delivery artifact pack from skill templates."
    )
    parser.add_argument("--out", required=True, help="Output directory to write files into.")
    parser.add_argument("--project", default="TBD", help="Project name.")
    parser.add_argument("--client", default="TBD", help="Client/company name.")
    parser.add_argument("--vendor", default="TBD", help="Delivery/vendor name.")
    parser.add_argument(
        "--version", default="0.1", help="Version string for generated artifacts."
    )
    parser.add_argument(
        "--date",
        default=_dt.date.today().isoformat(),
        help="Date string (default: today).",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite files if they already exist.",
    )
    parser.add_argument(
        "--full-structure",
        action="store_true",
        help="Create the full delivery package directory structure (templates, diagrams, doc, ppt, manifest).",
    )
    args = parser.parse_args(argv)

    skill_root = Path(__file__).resolve().parents[1]
    templates_dir = skill_root / "assets" / "templates"
    if not templates_dir.is_dir():
        print(f"ERROR: templates directory not found: {templates_dir}", file=sys.stderr)
        return 2

    out_dir = Path(args.out).expanduser().resolve()
    mapping = {
        "PROJECT_NAME": args.project,
        "CLIENT_NAME": args.client,
        "VENDOR_NAME": args.vendor,
        "VERSION": args.version,
        "DATE": args.date,
    }

    if args.full_structure:
        dirs = _create_directory_structure(out_dir)
        templates_out = dirs["templates"]
        (dirs["diagrams"] / "drawio").mkdir(exist_ok=True)
        (dirs["diagrams"] / "fireworks").mkdir(exist_ok=True)
        _write_readme(out_dir, mapping)
        print(f"[OK] Created full delivery package structure at {out_dir}")
    else:
        templates_out = out_dir

    template_paths = sorted(p for p in templates_dir.glob("*.md") if p.is_file())
    if not template_paths:
        print(f"ERROR: no templates found in {templates_dir}", file=sys.stderr)
        return 2

    wrote = 0
    for template_path in template_paths:
        rendered = _render(_read_text(template_path), mapping)
        out_path = templates_out / template_path.name
        _write_text(out_path, rendered, force=args.force)
        wrote += 1

    target_desc = f"full structure (templates + diagrams + doc + ppt + manifest)" if args.full_structure else f"templates only ({wrote} files)"
    print(f"[OK] Wrote {wrote} template files to {templates_out}")
    if args.full_structure:
        print(f"[OK] Delivery package structure: {target_desc}")
    print(f"[INFO] Next steps:")
    print(f"  1. Fill in templates in {templates_out}")
    print(f"  2. Produce diagrams per 08_diagram_manifest.md")
    print(f"  3. Compile deliverables per 07_deliverable_packaging.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
